// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCkJkBpDa5zoltA_vaPgGTmcIaDhJGPO0',
    appId: '1:508636983632:web:d69c361d2e0588c2ba7c55',
    messagingSenderId: '508636983632',
    projectId: 'mydb-fd774',
    authDomain: 'mydb-fd774.firebaseapp.com',
    storageBucket: 'mydb-fd774.firebasestorage.app',
    measurementId: 'G-Y18H1ET47V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrNcOmdtLiRjxRHbRo0BNWJKA9RQcIjOw',
    appId: '1:508636983632:android:3b33d444240bb6c7ba7c55',
    messagingSenderId: '508636983632',
    projectId: 'mydb-fd774',
    storageBucket: 'mydb-fd774.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA7sNKSyxJqcH8OjUFo570r4sbEQkqmN8',
    appId: '1:508636983632:ios:c2588648f5cf876eba7c55',
    messagingSenderId: '508636983632',
    projectId: 'mydb-fd774',
    storageBucket: 'mydb-fd774.firebasestorage.app',
    iosBundleId: 'com.example.sabak22FirebaseWithData',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA7sNKSyxJqcH8OjUFo570r4sbEQkqmN8',
    appId: '1:508636983632:ios:c2588648f5cf876eba7c55',
    messagingSenderId: '508636983632',
    projectId: 'mydb-fd774',
    storageBucket: 'mydb-fd774.firebasestorage.app',
    iosBundleId: 'com.example.sabak22FirebaseWithData',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCkJkBpDa5zoltA_vaPgGTmcIaDhJGPO0',
    appId: '1:508636983632:web:89bbc433b6be6dbaba7c55',
    messagingSenderId: '508636983632',
    projectId: 'mydb-fd774',
    authDomain: 'mydb-fd774.firebaseapp.com',
    storageBucket: 'mydb-fd774.firebasestorage.app',
    measurementId: 'G-64K6BHBL9H',
  );
}
